Portfolio.NETCore/Controllers/ExperienceController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portfolio.NETCore.Controllers
{
    public class ExperienceController : Controller
    {
        ExperienceManager experienceManager = new ExperienceManager(new EfExperienceDal());
        public IActionResult Index()
        {
            ViewBag.v1 = "Deneyim Listesi";
            ViewBag.v2 = "Deneyimler";
            ViewBag.v3 = "Deneyim Listesi";
            var values = experienceManager.TGetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddExperience()
        {
            ViewBag.v1 = "Deneyim Ekleme";
            ViewBag.v2 = "Deneyimler";
            ViewBag.v3 = "Deneyim Ekleme";
            return View();
        }
        [HttpPost]
        public IActionResult AddExperience(Experience experience)
        {
            experienceManager.TAdd(experience);
            return RedirectToAction("Index");
        }
        public IActionResult DeleteExperience(int id)
        {
            var values = experienceManager.TGetByID(id);
            experienceManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditExperience(int id)
        {
            ViewBag.v1 = "Düzenleme";
            ViewBag.v2 = "Deneyimler";
            ViewBag.v3 = "Deneyim Düzenleme";
            var values = experienceManager.TGetByID(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditExperience(Experience experience)
        {
            experienceManager.TUpdate(experience);
            return RedirectToAction("Index");
        }
    }
}

Portfolio.NETCore/Views/Experience/AddExperience.cshtml
@model EntityLayer.Concrete.Experience
@{
    ViewData["Title"] = "AddExperience";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

    @using (Html.BeginForm("AddExperience", "Experience", FormMethod.Post))
    {
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Deneyim Ekleme  Sayfası</h4>
                    <p class="card-description"> Basic form elements </p>
                    <form class="forms-sample">
                        <div class="form-group">
                            @Html.Label("Deneyim Başlığı")
                            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                          
                            @Html.Label("Deneyim Tarihi")
                            @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            @Html.Label("Deneyim Resmi")
                            @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            @Html.Label("Deneyim Açıklaması")
                            @Html.TextAreaFor(x => x.Description, 10, 3, new { @class = "form-control" })
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                        <button class="btn btn-dark">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    }

Portfolio.NETCore/Views/Experience/EditExperience.cshtml
@model EntityLayer.Concrete.Experience
@{
    ViewData["Title"] = "EditExperience";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="card-header border-0">
    <h1>Deneyim Düzenleme Sayfası</h1>
    @using (Html.BeginForm("EditExperience", "Experience", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.ExperienceID)
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Deneyim Düzenleme  Sayfası</h4>
                    <form class="forms-sample">
                        <div class="form-group">

                            @Html.Label("Deneyim Başlığı")
                            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                        </div>
                        <div class="form-group">

                            @Html.Label("Deneyim Tarihi")
                            @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            @Html.Label("Deneyim Resmi")
                            @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            @Html.Label("Deneyim Açıklaması")
                            @Html.TextAreaFor(x => x.Description, 10, 3, new { @class = "form-control" })
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                        <button class="btn btn-dark">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    }
</div>

Portfolio.NETCore/Views/Experience/Index.cshtml
@using EntityLayer.Concrete
@model List<Experience>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card ">
        <div class="card-body">
            <h4 class="card-title">Deneyimler Tablosu</h4>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col" class="sort text-white" data-sort="name">#</th>
                            <th scope="col" class="sort" data-sort="budget">Başlık</th>
                            <th scope="col" class="sort" data-sort="status">Tarih</th>
                            <th scope="col">Sil</th>
                            <th scope="col" class="sort" data-sort="completion">Düzenle</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th scope="row">
                                    <div class="text-white">
                                        @item.ExperienceID
                                    </div>
                                </th>
                                <th class="budget">
                                    @item.Name
                                </th>
                                <td>
                                    @item.Date
                                </td>
                                <td>
                                    <a href="/Experience/DeleteExperience/@item.ExperienceID" class="btn btn-outline-danger">Sil</a>
                                </td>
                                <td>
                                    <a href="/Experience/EditExperience/@item.ExperienceID" class="btn btn-outline-success">Güncelle</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<a href="/Experience/AddExperience/" class="btn btn-primary float-right">Yeni Deneyim Ekle</a>