Portfolio.NETCore/Controllers/SkillController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portfolio.NETCore.Controllers
{
    public class SkillController : Controller
    {
        SkillManager skillManager = new SkillManager(new EfSkillDal());
        
        public IActionResult Index()
        {
            ViewBag.v1 = "Yetenekler Listesi";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Listesi";
            var values = skillManager.TGetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddSkill()
        {
            ViewBag.v1 = "Yetenekler Ekleme";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Ekleme";
            return View();
        }
        [HttpPost]
        public IActionResult AddSkill(Skill skill)
        {
            skillManager.TAdd(skill);
            return RedirectToAction("Index");
        }
        public IActionResult DeleteSkill(int id)
        {
            var values = skillManager.TGetByID(id);
            skillManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditSkill(int id)
        {
            ViewBag.v1 = "Düzenleme";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Güncelleme";
            var values = skillManager.TGetByID(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditSkill(Skill skill)
        {
            skillManager.TUpdate(skill);
            return RedirectToAction("Index");
        }
    }
}

Portfolio.NETCore/Views/Skill/AddSkill.cshtml
@model EntityLayer.Concrete.Skill
@{
    ViewData["Title"] = "AddSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@using (Html.BeginForm("AddSkill", "Skill", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Yetenek Ekleme  Sayfası</h4>
                <form class="forms-sample">
                    <div class="form-group">
                        @Html.Label("Yetenek Başlığı")
                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.Label("Değer")
                        @Html.TextBoxFor(x => x.Value, new { @class = "form-control" })
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button class="btn btn-dark">Cancel</button>
                </form>
            </div>
        </div>
    </div>
}

Portfolio.NETCore/Views/Skill/EditSkill.cshtml
@model EntityLayer.Concrete.Skill
@{
    ViewData["Title"] = "EditSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}
@using (Html.BeginForm("EditSkill", "Skill", FormMethod.Post))
{
    @Html.HiddenFor(x => x.SkillID)
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Yetenek Düzenleme  Sayfası</h4>
                <form class="forms-sample">
                    <div class="form-group">
                        @Html.Label("Yetenek Başlığı")
                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.Label("Değer")
                        @Html.TextBoxFor(x => x.Value, new { @class = "form-control" })
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button class="btn btn-dark">Cancel</button>
                </form>
            </div>
        </div>
    </div>
}

Portfolio.NETCore/Views/Skill/Index.cshtml
@using EntityLayer.Concrete
@model List<Skill>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card ">
        <div class="card-body">
            <h4 class="card-title">Yetenek Listesi Tablosu</h4>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col" class="sort" data-sort="name">#</th>
                            <th scope="col" class="sort" data-sort="budget">Başlık</th>
                            <th scope="col" class="sort" data-sort="status">Oran</th>
                            <th scope="col">Sil</th>
                            <th scope="col" class="sort" data-sort="completion">Düzenle</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th scope="row">
                                    <div class="text-white">
                                        @item.SkillID
                                    </div>
                                </th>
                                <th class="budget">
                                    @item.Title
                                </th>
                                <td>
                                    <div class="progress">
                                        <div class="progress-bar bg-success" role="progressbar" aria-valuenow="@Convert.ToInt32(item.Value)" aria-valuemin="0" aria-valuemax="100" style="width: @item.Value%;">
                                            @item.Value
                                        </div>

                                    </div>
                                </td>
                                <td>
                                    <a href="/Skill/DeleteSkill/@item.SkillID" class="btn btn-danger">Sil</a>
                                </td>
                                <td>
                                    <a href="/Skill/EditSkill/@item.SkillID" class="btn btn-success">Güncelle</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<a href="/Skill/AddSkill/" class="btn btn-primary float-right">Yeni Yetenek Ekle</a>